package rules.agendagroup;
/*
  agenda-group ""
  default:无，需要使用Java设置
  type:String
  description: 议程分组，属于另一种可控的规则执行方式，是指用户可以通过配置agenda-group 的参数来控制规则执行
            而且只有获得焦点的 规则才会被激活

  注释事项：agenda-group 需要java代码进行focus激活，一般不推荐这么使用，存在java代码中未进行活着focus错误，导致规则永远不会被执行，
        因此在世纪使用中配合auto-focus使用
*/
rule "agenda-group_01"
    agenda-group "ag1"
    when
        eval(true)
    then
     System.out.println("【agenda-group_01】agenda-group \"ag1\" 执行了");
end

rule "agenda-group_02"
    agenda-group "ag2"
    when
        eval(true)
    then
     System.out.println("【agenda-group_02】agenda-group \"ag2\" 执行了");
end
/*多个规则中activation-group与agenda-group都相同时，当获取agendaa-group对应的focus,只执行salienc比较大的规则*/
rule "agenda-group_030"
    activation-group "activation01"
    agenda-group "agenda01"
    when
        eval(true)
    then
     System.out.println("【agenda-group_030】activation-group \"activation01\"\n" +
                                           "    agenda-group \"agenda01\" 执行了");
end

rule "agenda-group_031"
    activation-group "activation01"
    agenda-group "agenda01"
    salience 10
    when
        eval(true)
    then
     System.out.println("【agenda-group_031】activation-group \"activation01\"\n" +
                                           "    agenda-group \"agenda01\"\n" +
                                           "    salience 10 执行了");
end

/*多个规则中agenda-group都相同，activation-group不相同时，当获取agendaa-group对应的focus,两个规则都执行*/
rule "agenda-group_040"
    activation-group "activation02"
    agenda-group "agenda02"
    when
        eval(true)
    then
     System.out.println("【agenda-group_040】activation-group \"activation02\"\n" +
                                           "    agenda-group \"agenda02\" 执行了");
end

rule "agenda-group_041"
    activation-group "activation03"
    agenda-group "agenda02"
    salience 10
    when
        eval(true)
    then
     System.out.println("【agenda-group_041】activation-group \"activation03\"\n" +
                                           "    agenda-group \"agenda02\"\n" +
                                           "    salience 10 执行了");
end

/*多个规则中agenda-group不相同，activation-group相同时，当获取agendaa-group=agenda03对应的focus,执行agenda-group_050*/
//不会严格遵循在同一个激活组下salience大的执行
rule "agenda-group_050"
    activation-group "activation04"
    agenda-group "agenda03"
    when
        eval(true)
    then
     System.out.println("【agenda-group_050】activation-group \"activation04\"\n" +
                                           "    agenda-group \"agenda03\" 执行了");
end

rule "agenda-group_051"
    activation-group "activation04"
    agenda-group "agenda04"
    salience 10
    when
        eval(true)
    then
     System.out.println("【agenda-group_051】activation-group \"activation04\"\n" +
                                           "    agenda-group \"agenda04\"\n" +
                                           "    salience 10 执行了");
end
